# -*- coding: utf-8 -*-
"""Movie Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169_pSH34nitbgiuP97hNi_5AU1Km03WR

# **Movies Recommendation System**

**The Movies Recommendation System** is a machine learning project aimed at providing personalized movie suggestions to users based on their preferences and viewing history. Utilizing collaborative filtering and content-based filtering techniques, this system analyzes user behavior and movie attributes to generate accurate recommendations.

**Collaborative Filtering:** This technique predicts a user's interest by collecting preferences from multiple users. It assumes that if a user A has a similar taste to user B, and user B liked a particular movie, user A is likely to enjoy it too.

**Content-Based Filtering:** This method recommends movies based on the attributes of the films that a user has liked in the past, suggesting similar movies.

By leveraging advanced machine learning techniques and thorough data analysis, this Movies Recommendation System aims to deliver a highly personalized and enjoyable user experience.

# **Import Library**
"""

import pandas as pd

import numpy as np

dframe = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Movies%20Recommendation.csv')

dframe.head()

dframe.info()

dframe.shape

dframe.columns

"""# **Get Feature Selection**"""

dframe_features = dframe[['Movie_Genre','Movie_Keywords','Movie_Tagline', 'Movie_Cast','Movie_Director']].fillna('')

"""Selected five existing featires to recommend movies."""

dframe_features.shape

dframe_features

X = dframe_features['Movie_Genre'] + ' ' + dframe_features['Movie_Keywords'] + ' ' + dframe_features['Movie_Tagline'] +  ' ' + dframe_features['Movie_Cast'] + ' ' + dframe_features['Movie_Director']

X

X.shape

"""# **Get Features Text Convertion to Tokens**"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(X)

X.shape

print(X)

"""# **Get Similarity Score Consine Similarity**"""

from sklearn.metrics.pairwise import cosine_similarity

Similarity_score = cosine_similarity(X)

Similarity_score

Similarity_score.shape

"""# ***Get Movie Name as Input from User and Validate for Closet Spelling ***"""

Favourite_Movie_Name = input(" Enter your favourite movie name :")

All_Movies_Title_List = dframe['Movie_Title'].tolist()

import difflib

Movie_Recommendation = difflib.get_close_matches(Favourite_Movie_Name, All_Movies_Title_List)
print(Movie_Recommendation)

Close_Match = Movie_Recommendation[0]
print(Close_Match)

Index_of_Close_Match_Movie = dframe[dframe.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)

Recommendation_Score = list(enumerate(Similarity_score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)

len(Recommendation_Score)

"""# Get All Movies Sort Based on Recommendation Score"""

Sorted_Similar_Movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse = True)
print(Sorted_Similar_Movies)

print("Top 30 Movies Suggest for You ; \n")
i = 1

for movies in Sorted_Similar_Movies:
    index = movies[0]
    title_from_index = dframe[dframe.index==index]["Movie_Title"].values[0]

    if(i<31) :
      print(i, '.' ,title_from_index)
      i+=1

"""# Top 10 Movie Recommendation System"""

Movies_Name = input("Enter yout Favourite movie name : ")
list_of_all_titles = dframe['Movie_Title'].tolist()
Find_Close_Match = difflib.get_close_matches(Movies_Name, list_of_all_titles)
Close_Match = Find_Close_Match[0]
Index_of_Movie = dframe[dframe.Movie_Title == Close_Match]['Movie_ID'].values[0]
Recommendation_Score = list(enumerate(Similarity_score[Index_of_Movie]))
sorted_similar_movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse= True)

print("Top 10 Movies suggestes for you : \n")

i = 1

for movie in sorted_similar_movies :
    index = movie[0]
    title_from_index = dframe[dframe.Movie_ID==index]['Movie_Title'].values
    if (i<11):
      print(i, '.' ,title_from_index)
      i+=1